//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int q_ID { get; set; }
        public string Question1 { get; set; }
        public string O_A { get; set; }
        public string O_B { get; set; }
        public string O_C { get; set; }
        public string O_D { get; set; }
        public string Answer { get; set; }
    }
}
